services:
  node1:
    image: poa-node
    container_name: node1
    volumes:
      - ./build/node1:/root/.simapp
    command: simd start
    restart: unless-stopped
    ports:
      - 27656:26656
      - 26657:26657  # RPC
      - 9090:9090    # gRPC

  node2:
    image: poa-node
    container_name: node2
    volumes:
      - ./build/node2:/root/.simapp
    command: simd start
    restart: unless-stopped

  node3:
    image: poa-node
    container_name: node3
    volumes:
      - ./build/node3:/root/.simapp
    command: simd start
    restart: unless-stopped

  node4:
    image: poa-node
    container_name: node4
    volumes:
      - ./build/node4:/root/.simapp
    command: simd start
    restart: unless-stopped

  node5:
    image: poa-node
    container_name: node5
    volumes:
      - ./build/node5:/root/.simapp
    command: simd start
    restart: unless-stopped
