version: "3"

services:
  simdnode0:
    container_name: simdnode0
    image: "cosmos-sdk/simapp"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
      - LOG=${LOG:-simd.log}
    volumes:
      - ./build:/simd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  simdnode1:
    container_name: simdnode1
    image: "cosmos-sdk/simappnode"
    ports:
      - "26659-26660:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - ID=1
      - LOG=${LOG:-simd.log}
    volumes:
      - ./build:/simd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  simdnode2:
    container_name: simdnode2
    image: "cosmos-sdk/simapp"
    environment:
      - ID=2
      - LOG=${LOG:-simd.log}
    ports:
      - "26661-26662:26656-26657"
      - "1319:1317"
      - "9092:9090"
    volumes:
      - ./build:/simd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  simdnode3:
    container_name: simdnode3
    image: "cosmos-sdk/simapp"
    environment:
      - ID=3
      - LOG=${LOG:-simd.log}
    ports:
      - "26663-26664:26656-26657"
      - "1320:1317"
      - "9093:9090"
    volumes:
      - ./build:/simd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
