[package]
name = "zeropb"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
rend = { version = "0.4.1", default-features = false }
num_enum = { version = "0.7.1", default-features = false }
thiserror-no-std = "2.0.2"
lol_alloc = "0.4.0"