[package]
name = "ixc_vm_api"
version = "0.0.1"
edition = "2021"
repository.workspace = true
license.workspace = true

[dependencies]
ixc_message_api = { path = "../../message_api" }

[lints]
workspace = true
