[package]
name = "state_objects"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmossdk_core = {path = "../cosmossdk_core"}
dashu-int = "0.4.1"
