[package]
name = "state_objects_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.52", features = ["full"] }
quote = "1.0.35"
proc-macro2 = "1.0.78"
deluxe = "0.5.0"
