name: Documenation
on: [pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - uses: technote-space/get-diff-action@v1
        id: git_diff
        with:
          SUFFIX_FILTER: .md
          PREFIX_FILTER: docs/
      - name: Install and Build ğŸ”§
        run: |
          cd docs
          npm install
          npm run build

        # if: "env.GIT_DIFF != ''"
      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        env:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/.vuepress/dist
