name: Fix typos nightly

on:
  schedule:
    - cron: "0 8 * * *"
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: sobolevn/misspell-fixer-action@e5368f1b21585248afad4d32df9bc100451dbbff
      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PRBOT_PAT }}
          commit-message: "chore: fixes by misspell-fixer"
          title: "chore: typos fix by misspell-fixer"
