name: 'PR Go Mod Tidy and Mocks'
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}-pr-go-mod-tidy-mocks
  cancel-in-progress: true

jobs:
  go-mod-tidy:
    name: Check go mod tidy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 'latest'
      - name: Run go mod tidy
        run: ./scripts/go-mod-tidy-all.sh
      - name: Check for diffs
        run: |
          git diff --exit-code || {
            echo "Please run './scripts/go-mod-tidy-all.sh' and commit the changes";
            exit 1;
          }

  generate-mocks:
    name: Generate Mocks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 'latest'
      - name: Generate mocks
        run: make mocks
      - name: Check for diffs
        run: |
          git diff --exit-code || {
            echo "Please run 'make mocks' and commit the changes";
            exit 1;
          }
