name: Build & Push SDK Proto Builder
on:
  push:
    branches:
      - main
    paths:
      - "contrib/devtools/Dockerfile"
  pull_request:
    # paths:
      # - "contrib/devtools/Dockerfile"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cosmos/proto-builder

  # Allow one concurrent deployment
concurrency:
  group: "proto-docker"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # set VERSION to new version when making changes, when merged to main the image will automatically be pushed
      - uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # modify value when deploying a new version
          tags: |
            type=semver,pattern={{version}},value=v0.8.0 

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        # if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Publish to GHCR
        uses: docker/build-push-action@v3
        with:
          context: ./contrib/devtools
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
