name: Release Cosmovisor

on:
  push:
    tags:
      - "tools/cosmovisor/v*.*.*"
permissions:
  contents: read

jobs:
  goreleaser:
    permissions:
      contents: write # for goreleaser/goreleaser-action to create a GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      # get 'v*.*.*' part from 'cosmovisor/v*.*.*' and save to $GITHUB_ENV
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/cosmovisor/}" >> $GITHUB_ENV
      # remove the possible pre-existing same tag for cosmos-sdk related tags instead of cosmovisor tags
      # Because goreleaser enforces semantic versioning and will error on non compliant tags.(https://goreleaser.com/limitations/semver/)
      - name: Tag without prefix locally to avoid error in goreleaser
        run: |-
          git tag -d ${{ env.RELEASE_VERSION }} || echo "No such a tag exists before"
          git tag ${{ env.RELEASE_VERSION }} HEAD
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # stick to version v0.179.0(https://github.com/cosmos/cosmos-sdk/issues/11125)
          version: v0.179.0
          args: release --rm-dist --skip-validate --release-notes ./RELEASE_NOTES.md
          workdir: tools/cosmovisor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: cosmovisor/${{ env.RELEASE_VERSION }}
